Tech 7284 upgrade ruby and bundler
Invoca/activerecord-mysql-enum pull request #30
Opened 2022-03-30 20:17 UTC by gwynethallwright

2022-03-30 20:27 UTC, gwynethallwright commented
Let me know if you'd like to see the prerelease tested against a web build first.

2022-03-31 11:59 UTC, jebentier requested changes
It would be good to see at least a proof that the gem is passing in web before merging as a QA item.

2022-03-31 11:59 UTC, jebentier commented on .github/workflows/test.yml
> +        - gemfiles/rails_6.gemfile
There's no need to split between ruby 2 and ruby 3 like this just to exclude testing of rails 5 on ruby 3+. The `matrix` syntax allows the ability to do an `exclude` section so the matrix definition would look like the following:

```
matrix:
  ruby: [2.5, 2.6, 2.7, '3.0', 3.1]
  gemfile:
  - Gemfile
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_6.gemfile
  exclude:
  - ruby: '3.0'
    gemfile: gemfiles/rails_5.gemfile
  - ruby: 3.1
    gemfile: gemfiles/rails_5.gemfile
```

2022-03-31 11:59 UTC, jebentier commented on CHANGELOG.md
> +
No need to include project development environment changes as gem updates.
```suggestion
## [2.0.1] - Unreleased
### Added
- Added support for Ruby 3.0 and 3.1.

```

2022-03-31 16:09 UTC, gwynethallwright commented on .github/workflows/test.yml
> +        - gemfiles/rails_6.gemfile
Neat! Thanks.

2022-03-31 20:25 UTC, gwynethallwright commented
> It would be good to see at least a proof that the gem is passing in web before merging as a QA item.

Web build here: https://buildkite.com/invoca/web/builds/25494.

2022-04-01 13:56 UTC, jebentier commented on .github/workflows/test.yml
> +  test-ruby:
can we set this back to just `test`

2022-04-01 13:58 UTC, jebentier approved these changes
Everything looks good to me, thanks for linking the web build to prove out that this all works and is non-breaking. Once the minor change is made to the github workflow, feel free to merge.

2022-04-01 19:26 UTC, jebentier approved these changes

2022-04-01 20:02 UTC, merged